#!/usr/bin/env php
<?php

if (version_compare(phpversion(), '5.5.9', '<')) {
    echo "Coaster Framework: Can't run updateAsset script with PHP Version ".phpversion()." (5.5.9+ required)";
    exit;
}

require __DIR__ . '/../../../bootstrap/autoload.php';
$laravel_app = require __DIR__ . '/../../../bootstrap/app.php';

$kernel = $laravel_app->make(Illuminate\Contracts\Http\Kernel::class);
$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$coasterPublicFolder = public_path() . config('coaster::admin.public');
$updateFrom = __DIR__.'/public';

// update app folder
if (file_exists($coasterPublicFolder . '/app/')) {
    recursive_copy($updateFrom . '/app/', $coasterPublicFolder . '/app/');
    echo "Coaster Framework: Updated public coaster app assets\r\n";
}

function recursive_copy($src,$dst) {
    $dir = opendir($src);
    @mkdir($dst);
    while(false !== ( $file = readdir($dir)) ) {
        if (( $file != '.' ) && ( $file != '..' )) {
            if ( is_dir($src . '/' . $file) ) {
                recursive_copy($src . '/' . $file,$dst . '/' . $file);
            }
            else {
                copy($src . '/' . $file,$dst . '/' . $file);
            }
        }
    }
    closedir($dir);
}