<?php namespace CoasterCms\Libraries\Blocks;

use CoasterCms\Helpers\Cms\StringHelper;

class Richtext extends _Base
{

    public static function display($block, $block_data, $options = array())
    {
        if (!empty($options['length'])) {
            $block_data = strip_tags($block_data);
            return StringHelper::cutString($block_data, $options['length']);
        }
        return $block_data;
    }

    public static function edit($block, $block_data, $page_id = 0, $parent_repeater = null)
    {
        $block_data = htmlentities($block_data);
        return parent::edit($block, $block_data, $page_id, $parent_repeater); // TODO: Change the autogenerated stub
    }

}